### ISSUE TITLE
sir how can make discord bot from this can u help there is no slot bot token is ur main java

### ISSUE THREAD

**Issue by LATESTTIME** [WesRodgers/HQ-Trivia-Tool#1]

**Comment by WesRodgers** [comment]
I haven't gotten to that yet, in its current state all this is meant to do is access HQ's api, grab the websocket, and scrape the incoming question and choice data for Trivia and the hint/puzzle data for words. If someone wanted to make a discord chat bot from this they would need to create a discord chat bot that could listen in on what this is doing and use data from the question/puzzle objects. I'll be working on modularizing this appropriately to make that easier eventually, right now though this is still in very early development.
